### ISSUE TITLE
compatibility with OL 2.13?

### ISSUE THREAD

**Issue by c-pereira** [acanimal/AnimatedCluster#14]
Hi there,

are you planning to make some updates for the new version of OL? Would be great to see it there aswell. I love this animated cluster, but have some issues in 2.12 with flickering map tiles. 

kind regards

**Comment by acanimal** [comment]
Sorry, I bit late.
I tried it some months ago working on an implementation for OL3 but it is not as easy as I suppose.
I'm sorry :(
