### ISSUE TITLE
Clusters keep redrawing after showing popup

### ISSUE THREAD

**Issue by humpy125** [acanimal/AnimatedCluster#16]
I have added your AnimatedCluster code to a project I have been working on. I really like the way the animations work. 
I have noticed a problem, however, when zooming in on the map, the clusters are continually redrawn, making them flash on the map.  I have poked around inside AnimatedCluster.js and found that by changing this (at line 147 inside the cluster function):
                `if (resolution != this.resolution) {
                    this.zoomIn = (!this.resolution || (resolution <= this.resolution));
                }`

to:
                `if (resolution != this.resolution) {
                    this.zoomIn = (!this.resolution || ((resolution <= this.resolution)||(resolution > this.resolution)));
                }`

Stopped the flashing.

**Comment by acanimal** [comment]
Could you send a PR with code changes.
Thanks.

**Comment by acanimal** [comment]
Merged at #17
